version: "3.1"
services:

  api_nginx:
    image: nginx:alpine
    container_name: api_nginx
    restart: unless-stopped
    tty: true
    working_dir: /application
    volumes:
      - ./src:/application
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - api

  api_php:
    build: .
    container_name: api_php
    restart: unless-stopped
    tty: true
    working_dir: /application
    volumes:
      - ./src:/application
    networks:
      - api

networks:
  api:
    driver: bridge